### ISSUE TITLE
Map permission with Project admin

### ISSUE THREAD

**Issue by cmg1986** [codeclou/customfield-editor-plugin#25]
Hello, We are looking to manage permission to modify custom field values.
Like as of now, we need to grant access to users/group on every context for particular custom field which is again a big maintenance activity, need to add users/groups on lots of context for supported fields.
Is there a way to allow project admin can update custom field values themselves for their project custom field's context rather than to add them one by one.

Thanks
CM

**Comment by clouless** [comment]
unfortunately the internal code of the customfield contexts is not really straight forward
and at the point where I check for context permissions I have no way to tell if it is a project or the default context. There is no way to distinguish.

So at the moment this does not work.

But I will investigate and reopen this ticket, once I find a way to do it, since that sounds like an interesting feature.

**Comment by cmg1986** [comment]
You can also see the functionality of mentioned add-on which is having same capability.
https://marketplace.atlassian.com/plugins/nl.avisi.jira.plugins.edit-custom-field-values/server/overview
