### ISSUE TITLE
Custom field childoptions not working

### ISSUE THREAD

**Issue by danieledepetrini** [codeclou/customfield-editor-plugin#30]
Hi all,

I'm trying to add an option to an existing custom field but I receive an error performing PUT. Following are command I fired:

Read (working)

curl -X GET --header "Accept: application/json" --header "Authorization: Basic XXXXX" "https://hostname/rest/jiracustomfieldeditorplugin/1/user/customfields/10405/contexts/10514/options/10203/childoptions";echo
[{"optionvalue":"ST Legalmail","id":10216,"sequence":0,"disabled":false},{"optionvalue":"ST Amex","id":10217,"sequence":1,"disabled":false},{"optionvalue":"ST Anagrafe Rapporti Finanziari WEB","id":10218,"sequence":2,"disabled":false}]

Write (NOT working)
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" --header "Authorization: Basic XXXXXX" -d "{
  \"optionvalue\": \"ST Legalmail Enterprise\",
  \"id\": 10219,
  \"sequence\": 3,
  \"disabled\": false
}" "https://hostname/rest/jiracustomfieldeditorplugin/1/user/customfields/10405/contexts/10514/options/10203/childoptions";echo
{"message":"validation errors","statusCode":400,"subCode":400000,"errors":[{"name":"child.optionId","message":"No option found for supplied id."}]}

Any idea?

Thanks,

Daniele.

**Comment by clouless** [comment]
Hi,

If you want to use Create (POST) just not set the `id` and the `sequence` since they will get auto generated. Meaning this should work:

```
curl -X POST \
        --header "Content-Type: application/json" \
        --header "Accept: application/json" \
        --header "Authorization: Basic XXXXXX" \
        -d '{ "optionvalue": "ST Legalmail Enterprise", "disabled": false }' \
"https://hostname/rest/jiracustomfieldeditorplugin/1/user/customfields/10405/contexts/10514/options/10203/childoptions"
```
cheers

**Comment by danieledepetrini** [comment]
Thant's minor as well but still important: I meant the order in the web page, not in json.
One more, you should update the example JSON text in the POST section.

**Comment by clouless** [comment]
In the docs it is written there: https://codeclou.io/customfield-editor-plugin/1.4.0/rest-api/#endpoint-post23863383e6a437fddc302def2cbcd84f

Since the RestApiDoc is auto generated it is not so easy to use different json objects for Create and Update. But I will try to see if I can do it for future versions.

![image](https://user-images.githubusercontent.com/12599965/30555154-10f99182-9ca7-11e7-9910-a9796377b104.png)

And what do you mean by order on the webpage? You can use the SORT Enpoints to sort your elements.

**Comment by danieledepetrini** [comment]
POST with wrong order and example:

![screenshot-post](https://user-images.githubusercontent.com/5853013/30555858-2dbb2c34-9ca9-11e7-9bda-a9c942593b05.png)

GET with right order:

![screenshot-get](https://user-images.githubusercontent.com/5853013/30555857-2db9b566-9ca9-11e7-91a4-6ade738b2db2.png)

**Comment by clouless** [comment]
Ok now I know what you mean. But I think I cannot do anything about that since, that is https://swagger.io/ - a framework - I use and it seems to do that. But that order has nothing to do with the actual order. The API works fine, it is just the docs that are like this. Maybe swagger fixes that issue at some point. But thanks for pointing that out :)
