### ISSUE TITLE
Support for JIRA 7.5

### ISSUE THREAD

**Issue by davemidd** [codeclou/customfield-editor-plugin#33]
I have JIRA v7.5.0#75005 and the plugin (Version:1.4.0) is marked as 'Incompatible' by JIRA.
Do you have plans to support this version?
(vI.4 isn't mentioned here -https://marketplace.atlassian.com/plugins/jiracustomfieldeditorplugin/versions - so I'm not sure how I have it?)

Thanks,
David

**Comment by clouless** [comment]
hi david,
I fixed it. Seems the marketplace had some issues, now the 1.4.0 is public and can be installed for JIRA 7.5.0.

cheers,

**Comment by davemidd** [comment]
I already had 1.4 installed and it was/is marked as Incompatible.
![image](https://user-images.githubusercontent.com/1181083/30960723-c30fe4f2-a43b-11e7-840b-f58fdc6864ec.png)

**Comment by clouless** [comment]
Yes there seemed to have been something strange with the marketplace.
I can rest you assured that v1.4.0 of the plugin is tested and compatible to JIRA 7.5.0.

But since you seem to have installed it during the short period of time where the marketplace had issues, it now does not update the compatibility somehow.

Maybe if you uninstall and reinstall it the compatibility will show as compatible.

**Comment by davemidd** [comment]
Hmm, tried that.
![image](https://user-images.githubusercontent.com/1181083/30961393-efa4d976-a43d-11e7-8414-722764e78d92.png)

**Comment by clouless** [comment]
Ok the Marketplace does not seem to update it.
You might need to ignore the "incompatible" flag for now, since it is just a flag.
It does not mean anything further than that.

I updated the version before and any new installs of v1.4.0 on a JIRA 7.5.0 will surely not be marked incompatible.

![image](https://user-images.githubusercontent.com/12599965/30961507-af7f7f28-a446-11e7-81e5-c94b47ad7ce0.png)


So you have to live with the message for now.
In the next 2-3 weeks I will release v.1.5.0 and after installing that version the message will surely disappear. I am afraid I cannot do anymore about it right now.
