### ISSUE TITLE
REST call to add options to field takes a long time to complete

### ISSUE THREAD

**Issue by misterpk** [codeclou/customfield-editor-plugin#45]
### Please provide helpful information

Please have a look at the "How to Create an Issue" section on:

https://codeclou.io/customfield-editor-plugin/redirect/?/latest/issue-tracker/#howto

We have a field that we need to update with a bunch of options. Currently it takes about 6 seconds for each rest call to post to the field. With 1000 items to add, this takes a very long time. Do you have a way of adding things in bulk? Should each call take 6 seconds?

**Comment by clouless** [comment]
Hi,

Since I call the exact same JIRA API when adding an option as JIRA itself does I would guess that is a Problem of underlying database or any other bottleneck. I have never heard of such behaviour.
Does it also take 6 seconds when you update/create an option via the built in JIRA Customfield Editor?

**Comment by misterpk** [comment]
I'm not sure. I will have to try this when I get back to the office on
Monday, however if you are using the same JIRA API, then I'm sure it will.
Thanks for answering my question!

**Comment by clouless** [comment]
Ok :)
And if it really turns out as a problem with my Plugin please send me more info about your setup, so I can try to figure out what is wrong. 
Database, OS (Linux/Winows), Ram, CPU, Is database on same Host, How big is the Instance (how many jira users) a.s.o

It is also always a good idea to perform the [built in JIRA Health Checks](https://confluence.atlassian.com/support/instance-health-790796828.html)

**Comment by clouless** [comment]
closing due to no further feedback.
