### ISSUE TITLE
api access without edit permission

### ISSUE THREAD

**Issue by Tobbe08** [codeclou/customfield-editor-plugin#49]
Hi
I made a comment at the marketplace and would like to clarify.
As a logged in user you have access to all api GET protocol. It would be nice it it worked the same way wit this plugin because of now I have to give edit access in order to give read access (GET).

some integrations to other tools, or reports need to get data but the user should not have access to edit.
I hope this cleared some thing up.

thanks

**Comment by clouless** [comment]
hi,

Yes I understand that this is the way the default JIRA Endpoints work.
But I cannot open security holes by default by exposing all customfields to all users by default.
It is intended to work the way it works and it is described in the Admin Documentation:
https://codeclou.io/customfield-editor-plugin/1.7.1/administrator-guide/

In the JIRA built in mechanism only an administrator can change customfields and that should stay this way. Only if an admin gives a user willingly the permission via this plugin to read/edit the values he can do so. Most users simply create themeselves an api user that gets permissions for all the fields. You could also script yourself a simple script to add permissions for that user on all customfields.

As an jira-admin you can call all `/admin/*` endpoints and simply do:

(1) Get all customfields via admin user `GET /admin/customfields`
(2) Iterate over result and call in a loop

```
for (field in fields) {
  PUT /admin/customfields/{field.id}
  WITH BODY: { "userlist": [ "my-api-user"  ] }
}
```

This would give your api user simply permission to all customfields.

So it works as expected.

What one could think of would be a Global setting you could set to enable read access to all customfield GET Endpoints. But that would take some time to implement I would need time to think about if this is a feature that benefits the plugin and if other people are also interested.

**Comment by clouless** [comment]
I had time to think about everything and came to the conclusion that permission handling for the plugin will stay how it is. There will be no "global read all customfields" option in the future.

And here is why:
Let's compare the customfield rest api this plugin provides to the issues rest api JIRA itself provides.
And let's also state that I am an Atlassian Certified JIRA Administrator (ACP-100), so I know a lot of big JIRA installations for big companies and have also worked on small installations.
In big companies JIRA projects are usually separated from each other by a project permission scheme that has roles that map to groups. Let's say team-alpha can only work on project-y and team-beta can only work on project-z.

If now a team member of team-alpha uses the JIRA Rest API to fetch issues, it will only get issues from project-y and project-z issues will not be accessible. It is the same the other way round.
So your statement is not fully correct to say that a normal user can fetch(read) everything via the REST Api. It might be true in a standard installation where everyone who is in group `jira-developer` can view every project because they share the same permission scheme and roles that map to jira-devloper group. But this is just the case for small installations. Usually big companies (who mainly use the plugin) want to separate projects and also want to separate customfields by projects or user groups.

Also you need to take into account that a customfield is a somewhat loosely global entity. It can live without and project. It can be shared for 1 or more projects. So it is not so easy to implement security in the first place. Also there are customfield contexts which let you share one customfield with many projects and different values.

As a certified administrator I can tell you that a robuts JIRA setup relies on user groups that are mapped to project roles. Usually you would have groups that correspond to your projects names.
These groups can then also be used to give permissions for customfields either for the whole customfield (all contexts) or specific contexts.

I hope this explains why we choose this type of behaviour and "strict" permission handling :)
