### ISSUE TITLE
Customfield Permissions - High Number of Users in Select Field Causes Problems

### ISSUE THREAD

**Issue by ldolloff** [codeclou/customfield-editor-plugin#6]
While trying to edit Customfield Permissions, the high number of users in our system causes the plugin to timeout.  The customfield name does not appear and the user list remains empty.

**Error Message:** Uncaught RangeError: Maximum call stack size exceeded
**Number of JIRA Users:** 152,875
**Number of JIRA Groups:**  296

![screen shot 2016-04-18](https://cloud.githubusercontent.com/assets/16785082/14612707/3f81addc-055e-11e6-9f85-6ff46370bd6c.png)

**Comment by gruenebe** [comment]
I am sorry that you have such an error. But it seems you are using version 1.1 and there will be no bugfixes for v1.1.
In version 1.2+ for JIRA 7+ this problem is not existing anymore since there is no full list of users and groups rendered anymore. The complete GUI has been rewritten in v1.2 to avoid such problems.

**Comment by gruenebe** [comment]
since in v1.1 one cannot set permission via the API (this feature was also introduced in v1.2)
the only possibility you have is to insert an option manually via the Developer Toolbar.

But there is one "hacky" way that could work. You could try to use the Chrome developer toolbar
to manually insert usernames or groups you want to set permissions for. And then click save.
I am not 100% sure that works but it is worth a try.

This is basically the way it works:
![insert-option](https://cloud.githubusercontent.com/assets/12599965/14613388/89e04e0e-059c-11e6-8865-738c834a6949.gif)

**Comment by zarfmouse** [comment]
Thanks for the workaround we'll try that. 

Unfortunately while 1.2.x looks much improved, we can not yet upgrade to JIRA 7.x because of plugins we use which have not yet been upgraded to work with JIRA 7.x. We'll adopt 1.2.x as soon as we're able to adopt JIRA 7.x but that may be months away. 

Thanks!

**Comment by gruenebe** [comment]
Ok I just checked the old code and my suggested workaround should work since the template looks like this.

![image](https://cloud.githubusercontent.com/assets/12599965/14613862/a85704a2-059e-11e6-84d6-6f6b7c96c9a3.png)

So I hope you can live with the workaround for now.

**Comment by zarfmouse** [comment]
I found an easier workaround, it seems that this client side error occurs on Chrome but not on Firefox. On Firefox it is clunky and slow but it doesn't just give up.

**Comment by gruenebe** [comment]
Unusual for Firefox to be able to render any website without freezing completely  ....
But goof to hear :)
