### ISSUE TITLE
Support for Datacenter

### ISSUE THREAD

**Issue by sandiptasucharita** [codeclou/customfield-editor-plugin#60]
We are planning to use this plugin. Is this supported for Jira datacenter?

**Comment by clouless** [comment]
Hi,

You can use it for DataCenter if your instance is not so big. Around 1000 customfields should work fine.
The load when using the admin permission editor list can be high when you have more fields. (Because there is currently no pagination)

I am currently working on the official support for it. So if you want to wait you can watch Issue: #51 

Cheers,
Bernhard
